//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternationalMovile.Clases
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturas
    {
        public int ID_Factura { get; set; }
        public string Cliente { get; set; }
        public int Cant_Articulos { get; set; }
        public decimal Monto_Factura { get; set; }
        public System.DateTime Fecha { get; set; }
        public string vendedor { get; set; }
        public string NCF { get; set; }
        public string TipoNCF { get; set; }
        public string TipoPago { get; set; }
        public string ReferenciaDePago { get; set; }
        public decimal Monto { get; set; }
        public Nullable<bool> Anulada { get; set; }
        public string Tipo_Documento { get; set; }
    }
}
