//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternationalMovile.Clases
{
    using System;
    using System.Collections.Generic;
    
    public partial class GastosPerdidas
    {
        public int ID_ReporteGastosPerdidas { get; set; }
        public string Motivo { get; set; }
        public decimal Monto { get; set; }
        public System.DateTime FechaReporte { get; set; }
        public string Usuario { get; set; }
        public string Comentario { get; set; }
    }
}
