//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternationalMovile.Clases
{
    using System;
    using System.Collections.Generic;
    
    public partial class GastosPerdidas
    {
        public int ID_ReporteGastosPerdidas { get; set; }
        public string Motivo { get; set; }
        public decimal Monto { get; set; }
        public System.DateTime FechaReporte { get; set; }
        public string Usuario { get; set; }
        public string Comentario { get; set; }
    }
}
