//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternationalMovile.Clases
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IM_DB_Entities : DbContext
    {
        public IM_DB_Entities()
            : base("name=IM_DB_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Cargos> Cargos { get; set; }
        public DbSet<Clases_Productos> Clases_Productos { get; set; }
        public DbSet<Clientes> Clientes { get; set; }
        public DbSet<Facturas> Facturas { get; set; }
        public DbSet<GastosPerdidas> GastosPerdidas { get; set; }
        public DbSet<NCFs> NCFs { get; set; }
        public DbSet<Nombres_Productos> Nombres_Productos { get; set; }
        public DbSet<Nota_Credito> Nota_Credito { get; set; }
        public DbSet<Parametros_Generales> Parametros_Generales { get; set; }
        public DbSet<Productos> Productos { get; set; }
        public DbSet<Productos_V> Productos_V { get; set; }
        public DbSet<Tipo_Pago> Tipo_Pago { get; set; }
        public DbSet<Tipos_ID_Cliente> Tipos_ID_Cliente { get; set; }
        public DbSet<Users> Users { get; set; }
        public DbSet<VentaInmediata> VentaInmediata { get; set; }
        public DbSet<Ventas> Ventas { get; set; }
    }
}
