//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternationalMovile.Clases
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nota_Credito
    {
        public int ID_Nota_Credito { get; set; }
        public string Numero_NCF { get; set; }
        public string NCF_Modificado { get; set; }
        public int Id_Tipo_NCF { get; set; }
        public string Id_Cliente { get; set; }
        public Nullable<int> Tipo_Cliente { get; set; }
        public string Anio_Mes { get; set; }
        public string Dia { get; set; }
        public Nullable<decimal> Itebis { get; set; }
        public Nullable<decimal> Monto { get; set; }
    }
}
