//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternationalMovile.Clases
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        public string ID_Producto { get; set; }
        public int NombreProducto { get; set; }
        public int Clase { get; set; }
        public decimal Precio_Costo { get; set; }
        public System.DateTime Fecha_Ingreso { get; set; }
    }
}
