//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternationalMovile.Clases
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos_V
    {
        public string ID_Producto { get; set; }
        public int NombreProducto { get; set; }
        public int Clase { get; set; }
        public decimal Precio_Costo { get; set; }
        public System.DateTime Fecha_Ingreso { get; set; }
    }
}
