//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternationalMovile.Clases
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int Usr_ID { get; set; }
        public string Login_Name { get; set; }
        public string Login_Pass { get; set; }
        public string Nombre { get; set; }
        public string Cedula { get; set; }
        public string Telefono_Movil { get; set; }
        public string Telefono_Local { get; set; }
        public string Direccion { get; set; }
        public Nullable<int> Cargo { get; set; }
    }
}
