//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternationalMovile.Clases
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int Usr_ID { get; set; }
        public string Login_Name { get; set; }
        public string Login_Pass { get; set; }
        public string Nombre { get; set; }
        public string Cedula { get; set; }
        public string Telefono_Movil { get; set; }
        public string Telefono_Local { get; set; }
        public string Direccion { get; set; }
        public Nullable<int> Cargo { get; set; }
    }
}
