//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternationalMovile.Clases
{
    using System;
    using System.Collections.Generic;
    
    public partial class VentaInmediata
    {
        public int Id_Venta { get; set; }
        public Nullable<int> factura { get; set; }
        public Nullable<int> id_Nombre_Producto { get; set; }
        public string IMEI { get; set; }
        public Nullable<decimal> precio { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    }
}
